web/FarmaciaTurno/config/routes.rb
Rails.application.routes.draw do

  resources :farmacia
  namespace :api do
      namespace :v1 do
        resources :users
      end
    end

  get 'farmacia_turno/index'
  get 'allFarmacias' => 'farmacia#allFarmacias'
  get 'migrador/migrar'
  get 'mapa' => 'prueba#martin'
  get 'devolver' => 'ajax#devolver'
  post   'migrar' => 'farmacia#migrar'
  get 'nose'=> 'ajax#index'

  root 'farmacia#index'

end

web/FarmaciaTurno/app/models/article.rb
class Article < ActiveRecord::Base
end

web/FarmaciaTurno/app/models/farmacia.rb
class Farmacia < ActiveRecord::Base
  has_and_belongs_to_many :tipo
end

web/FarmaciaTurno/app/models/farmacia_tipo.rb
class FarmaciaTipo < ActiveRecord::Base
end

web/FarmaciaTurno/app/models/farmacium.rb
class Farmacium < ActiveRecord::Base


end

web/FarmaciaTurno/app/models/tipo.rb
class Tipo < ActiveRecord::Base
   has_and_belongs_to_many :farmacia
end

web/FarmaciaTurno/app/models/user.rb
class User < ActiveRecord::Base
end

web/FarmaciaTurno/app/controllers/ajax_controller.rb
class AjaxController < ApplicationController



def index



end


def devolver

  @josefo="200Ok"

  @farmacium = Farmacium.new(get_post_parameters)
  @farmacium.save
  respond_to do |format|
     format.html
     format.json { render json: @josefo }
   end
end


private
def get_post_parameters
  params.permit( :nombre, :direccion, :letra, :telefono, :urlMaps, :urlWeb, :latitud, :longitud, :horario, :observaciones)
end


end

web/FarmaciaTurno/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/FarmaciaTurno/app/controllers/farmacia_controller.rb
class FarmaciaController < ApplicationController
  before_action :set_farmacium, only: [:show, :edit, :update, :destroy]

  # GET /farmacia
  # GET /farmacia.json
  def index
    @farmacias = Farmacium.all
  end

  # GET /farmacia/1
  # GET /farmacia/1.json
  def show
  end

  # GET /farmacia/new
  def new
    @farmacium = Farmacium.new
  end

  # GET /farmacia/1/edit
  def edit
  end

  # POST /farmacia
  # POST /farmacia.json
  def create
    @farmacium = Farmacium.new(farmacium_params)

    respond_to do |format|
      if @farmacium.save
        format.html { redirect_to @farmacium, notice: 'Farmacium was successfully created.' }
        format.json { render :show, status: :created, location: @farmacium }
      else
        format.html { render :new }
        format.json { render json: @farmacium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmacia/1
  # PATCH/PUT /farmacia/1.json
  def update
    respond_to do |format|
      if @farmacium.update(farmacium_params)
        format.html { redirect_to @farmacium, notice: 'Farmacium was successfully updated.' }
        format.json { render :show, status: :ok, location: @farmacium }
      else
        format.html { render :edit }
        format.json { render json: @farmacium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmacia/1
  # DELETE /farmacia/1.json
  def destroy
    @farmacium.destroy
    respond_to do |format|
      format.html { redirect_to farmacia_url, notice: 'Farmacium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def allFarmacias

    @user = Farmacium.all
    @variable = Array.new

    @user.each do |farmacia|

        if farmacia.letra.match("I")
          farmacia.deTurno = "assets/farmredGreenNew.png"
        else
          farmacia.deTurno ="assets/farmRedNew.png"
        end
        @variable.push(farmacia)

    end

    respond_to do |format|
      format.json { render :json => @variable, :status => 200}
      format.json {render :json => true}


    end


  end

  def migrar
    @parametro = params.require(:farma).permit(:direccion, :nombre)

    respond_to do |format|
      format.json { render :json => @parametro, :status => 200}
      format.json {render :json => true}


    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farmacium
      @farmacium = Farmacium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farmacium_params
      params.require(:farmacium).permit(:latitud, :longitud, :nombre, :letra, :direccion, :telefono, :urlMaps, :urlWeb, :coords, :horario, :observaciones)
    end
end

web/FarmaciaTurno/app/controllers/hello_message_controller.rb
class HelloMessageController < ApplicationController

web_service_api HelloMessageApi
 web_service_dispatching_mode :direct
  wsdl_service_name 'hello_message'
   web_service_scaffold :invoke

  def hello_message(firstname, lastname)
    return "Hello "+ firstname +" "+lastname
  end
end

web/FarmaciaTurno/app/controllers/migrador_controller.rb
class MigradorController < ApplicationController


  def migrar

    @farmacias = Farmacium.all

    @farmacias.each do |farmacia|

      coords = farmacia.coords.split(",")
      farmacia.latitud = coords[0]
      farmacia.longitud =coords[1]
      farmacia.save
    end


  end

end

web/FarmaciaTurno/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def bienvenido
    @martin =Array.new
    farmacia = Farmacia.new
    farmacia.direccion = "2 nro 190 E/ 35 Y 36"
    farmacia.latitud= "-34.898910"
    farmacia.nombre ="Farmacia Franco"
    farmacia.longitud = "-57.959542"
    farmacia.telefono="0221 489-1773"
    farmacia.urlMaps="https://www.google.com.ar/maps/place/Calle+2+190,+B1902CHH+La+Plata,+Buenos+Aires/@-34.8989498,-57.9617145,17z/data=!3m1!4b1!4m5!3m4!1s0x95a2e653053a24f7:0xac34b441c99cfae3!8m2!3d-34.8989542!4d-57.9595312?hl=es-419"
    @martin.push farmacia
#    @martin.push "-34.898910,-57.959542"
#    @martin.push "-34.919332,-57.934647"
#    @martin.push "-34.915223,-57.944679"
  end

end

web/FarmaciaTurno/app/helpers/ajax_helper.rb
module AjaxHelper
end

web/FarmaciaTurno/app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

web/FarmaciaTurno/app/helpers/application_helper.rb
module ApplicationHelper
end

web/FarmaciaTurno/app/helpers/farmacia_helper.rb
module FarmaciaHelper
end

web/FarmaciaTurno/app/helpers/farmacia_turno_helper.rb
module FarmaciaTurnoHelper
end

web/FarmaciaTurno/app/helpers/migrador_helper.rb
module MigradorHelper
end

web/FarmaciaTurno/app/helpers/prueba_helper.rb
module PruebaHelper
end

web/FarmaciaTurno/app/helpers/welcome_helper.rb
module WelcomeHelper
end

web/FarmaciaTurno/app/views/farmacia/_form.html.erb
<%= form_for(@farmacium) do |f| %>
  <% if @farmacium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farmacium.errors.count, "error") %> prohibited this farmacium from being saved:</h2>

      <ul>
      <% @farmacium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
  <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :letra %><br>
    <%= f.text_field :letra %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :urlMaps %><br>
    <%= f.text_field :urlMaps %>
  </div>
  <div class="field">
    <%= f.label :urlWeb %><br>
    <%= f.text_field :urlWeb %>
  </div>
  <div class="field">
    <%= f.label :coords %><br>
    <%= f.text_field :coords %>
  </div>
  <div class="field">
    <%= f.label :horario %><br>
    <%= f.text_field :horario %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br>
    <%= f.text_field :observaciones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/FarmaciaTurno/app/views/farmacia/edit.html.erb
<h1>Editing Farmacium</h1>

<%= render 'form' %>

<%= link_to 'Show', @farmacium %> |
<%= link_to 'Back', farmacia_path %>

web/FarmaciaTurno/app/views/farmacia/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>GMaps.js &mdash; Mapa Basico</title>
  <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true"></script>



  <script type="text/javascript">
var map;
var latitudActual;
var longitudActual;

function createRoute(latitud,longitud){
  map.cleanRoute();
  map.drawRoute({
    origin: [latitudActual, longitudActual],
    destination: [latitud, longitud],
    travelMode: 'walking',
    strokeColor: '#131540',
    strokeOpacity: 0.6,
    strokeWeight: 6
  });
}

function getUbicacion(){
  GMaps.geolocate({
  success: function(position) {
    latitudActual = position.coords.latitude;
    longitudActual = position.coords.longitude;
    map.setCenter(position.coords.latitude, position.coords.longitude);
    map.addMarker({
      lat: position.coords.latitude,
      lng: position.coords.longitude,
      title: 'posicion actual',
      });
  },

  error: function(error) {
    alert('Geolocation failed: '+error.message);
  },
  not_supported: function() {
    alert("Your browser does not support geolocation");
  },

});
}
function getFarmacias(){
  $.ajax({
    type: 'GET',
    url :'/allFarmacias',
     dataType : 'html',
     success: function(data){
     console.log("success");
  data = jQuery.parseJSON(data);
     //var farmacia = data[0];

     $(data).each(function(index,farmacia){
       console.log("asdasd");
       console.log(farmacia.deTurno);
       console.log("asdasd");
       console.log(index);
       console.log(farmacia.latitud);
        if(farmacia.latitud != null){

       map.addMarker({
         lat: farmacia.latitud,
         lng: farmacia.longitud,
         icon : farmacia.deTurno,
         title: farmacia.nombre,
         click: function(e) {

          swal({
              title: farmacia.nombre,
              text: "Direccion: "+farmacia.direccion+" Telefono:"+farmacia.telefono+" Horario:"+farmacia.horario+" Observaciones: "+farmacia.obeservaciones+" Letra: "+farmacia.letra,
              type: "success",
              showCancelButton: true,
              confirmButtonColor: "green",
              confirmButtonText: "Ir",
              cancelButtonText: "Volver",
              closeOnConfirm: true,
              closeOnCancel: true
            },
            function(isConfirm){
              if (isConfirm) {
                createRoute(farmacia.latitud,farmacia.longitud)
              }
            });


         }
       });


     }else{

     }
     });

  },
    error : function(error){
      console.log("error");
      alert("Error al cargar las farmacias");

    }
  });

}



   $(document).ready(function(){
     map = new GMaps({
       div: '#map',
       lat: -34.921178,
       lng: -57.954629,
       zoom: 14,
       zoomControl : false,
       panControl : false,
       streetViewControl : false,
       mapTypeControl: false,
       minZoom: 14
     });

getFarmacias();
getUbicacion();

   });
 </script>
 <style>
 body{
 font-family: Helvetica, Arial, sans-serif;
 margin:1em;
}
#map{
 display: block;
 width: 94%;
 height: 650px;
 margin: 4em auto;
 -moz-box-shadow: 0px 5px 20px #ccc;
 -webkit-box-shadow: 0px 5px 20px #ccc;
 box-shadow: 0px 5px 20px #ccc;
}

 </style>
</head>
<body>



     <div id="map"></div>
</body>

   </html>

web/FarmaciaTurno/app/views/farmacia/migrar.html.erb
<h1> hello </h1>

web/FarmaciaTurno/app/views/farmacia/new.html.erb
<h1>New Farmacium</h1>

<%= render 'form' %>

<%= link_to 'Back', farmacia_path %>

web/FarmaciaTurno/app/views/farmacia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitud:</strong>
  <%= @farmacium.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @farmacium.longitud %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @farmacium.nombre %>
</p>

<p>
  <strong>Letra:</strong>
  <%= @farmacium.letra %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @farmacium.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @farmacium.telefono %>
</p>

<p>
  <strong>Urlmaps:</strong>
  <%= @farmacium.urlMaps %>
</p>

<p>
  <strong>Urlweb:</strong>
  <%= @farmacium.urlWeb %>
</p>

<p>
  <strong>Coords:</strong>
  <%= @farmacium.coords %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @farmacium.horario %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @farmacium.observaciones %>
</p>

<%= link_to 'Edit', edit_farmacium_path(@farmacium) %> |
<%= link_to 'Back', farmacia_path %>

web/FarmaciaTurno/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FarmaciaTurno</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/FarmaciaTurno/app/views/migrador/migrar.html.erb
<h1> migracion realizada con exitó</h1>